from enum import Enum

class View(Enum):
    MAIN_WINDOW = "MAIN_WINDOW"
    PATIENT_DETAIL = "PATIENT_DETAIL"
    PATIENT_REGISTRATION = "PATIENT_REGISTRATION"
    MEDICAL_RECORD_DETAIL = "MEDICAL_RECORD_DETAIL"
    MEDICAL_RECORD_READ = "MEDICAL_RECORD_READ"
    NEW_ENTRY = "NEW_ENTRY"
    LOGS_WINDOW = "LOGS_WINDOW"
    ALL_PATIENTS = "MAIN_WINDOW"