from enum import Enum

class View(Enum):
    MAIN_WINDOW = "MAIN_WINDOW"
    PATIENT_DETAIL = "PATIENT_DETAIL"
    PATIENT_REGISTRATION = "PATIENT_REGISTRATION"
    MEDICAL_RECORD_DETAIL = "MEDICAL_RECORD_DETAIL"
    NEW_ENTRY = "NEW_ENTRY"