from .Date import Date
from .Datetime import Datetime
from .Dni import Dni
from .Email import Email
from .Gender import Gender
from .Health_insurance import Health_insurance
from .Id import Id
from .Last_name import Last_name
from .Name import Name
from .Phone import Phone
from .Text_with_range import Text_with_range
from .Value_object import Value_object